name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libasound2-dev libjack-jackd2-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DBUILD_TESTING=ON

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
